version: 0.2

env:
  variables:
    project_version: "1.0-SNAPSHOT"

phases:
  pre_build:
    - gradle check
  install:
    - gradle shadowJar
artifacts:
  files:
    - build/libs/spark-rest-example*.jar